export const GET_PRODUCTS = 'GET_PRODUCTS'
export const CHANGE_NAV = 'CHANGE_NAV'
export const GET_SINGLE = 'GET_SINGLE'
export const CHANGE_CART = 'CHANGE_CART'
export const GET_SITE = 'GET_SITE'
export const LOGIN = 'LOGIN'
export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'