export const GET_PRODUCTS = 'GET_PRODUCTS'
export const CHANGE_NAV = 'CHANGE_NAV'
export const GET_SINGLE = 'GET_SINGLE'
export const TO_CART = 'TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const GET_SITE = 'GET_SITE'
export const LOGIN = 'LOGIN'